"""rename address

Revision ID: c469736f3223
Revises: 3f503a5279b1
Create Date: 2024-05-14 20:13:17.342855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c469736f3223'
down_revision = '3f503a5279b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###

    # commands created by db.migrate originally are lines 24-26 add the column location, but drop 'address with it associated data
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
    #     batch_op.drop_column('address')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###

    # commands created by db.migrate originally
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')
